### ISSUE TITLE
pre-train teahcer model epochs?

### ISSUE THREAD

**Issue by SakurajimaMaiii** [cchen-cc/PMKL#3]
Thanks for your contribution.
I have a question about training.
It seem like that main.py only includes student-model training.
I could not find the epochs of pre-train teacher model. (May miss sth ?)
Could you share epochs/iterations of pre-train teacher model ?
Thanks for your help.

**Comment by cchen-cc** [comment]
We used the teacher model obtained around 50,000 iterations.

**Comment by SakurajimaMaiii** [comment]
> 

thanks
